apiVersion: v1
kind: Service
metadata:
  name: stroke-prediction #name of the sservice
spec:
  type: LoadBalancer
  selector:
    app: stroke-prediction #which pods qualify for forwarding ]
  ports:
  - port: 80 #port on service external
    targetPort: 8000 # port on the pod 
